### ISSUE TITLE
Shortcut change possible? 😃

### ISSUE THREAD

**Issue by illustree** [mohamed-arradi/Darky#3]
Hi there, first of all, thanks! awesome tool! I use it every day ... just I can't remember the shortkey 🙈 ... why is it actually the “B” ? and not the “D” for Dark? or can you make it customisable? thanks a lot ...

**Comment by mohamed-arradi** [comment]
Hi ! Thank you very much for the appreciation of this software. Yeah you may have right the D should have been better but most of all, the customization too. It will be on the next release !

**Comment by mohamed-arradi** [comment]
@illustree I have updated the App and the binary on the release section. The shortcut now is CMD + D. I assume it is more simpler and make more sense

It is not customizable yet, I need to look for to see how to do it properly.

I close this issue but i don't forget the idea of making customizable.
